/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import Controller.Administrador;
import sistemareservahospedajes.Menu;
import sistemareservahospedajes.Menu;

/**
 *
 * @author DELL
 */
public class FormularioPlataforma extends javax.swing.JFrame {

    /**
     * Creates new form FormularioPlataforma
     */
    /*  CREANDO LISTA AUXILIAR que permitira almacenar los datos leidos del 
            archivo administradores.txt */
    
    List<Administrador> listaAuxAdministradores = new ArrayList<Administrador>();
    public FormularioPlataforma() {
        initComponents();
        setLocationRelativeTo(null); // ubica la ventana en medio de la pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sistemaReservaHospedajes1 = new sistemareservahospedajes.SistemaReservaHospedajes();
        backGround = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        btnIngresar = new javax.swing.JLabel();
        Ingresar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        backGround.setBackground(new java.awt.Color(255, 255, 255));
        backGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SunWayLogo.jpg"))); // NOI18N
        logo.setText("jLabel2");
        backGround.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 480));

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("INICIAR SESIÓN");
        backGround.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(92, 182, 120));
        jLabel2.setText("USUARIO");
        backGround.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, -1, -1));

        txtUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(204, 204, 204));
        txtUsuario.setText("Ingrese su nombre de usuario");
        txtUsuario.setBorder(null);
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioMousePressed(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        backGround.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        backGround.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 260, 10));

        jLabel3.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(92, 182, 120));
        jLabel3.setText("CONTRASEÑA");
        backGround.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, -1, -1));

        txtContraseña.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtContraseña.setForeground(new java.awt.Color(204, 204, 204));
        txtContraseña.setText("****************");
        txtContraseña.setBorder(null);
        txtContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtContraseñaMousePressed(evt);
            }
        });
        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        backGround.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 200, -1));

        jSeparator3.setBackground(new java.awt.Color(91, 185, 123));
        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));
        backGround.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 260, 10));

        jPanel1.setBackground(new java.awt.Color(252, 173, 29));
        jPanel1.setForeground(new java.awt.Color(252, 173, 29));

        btnIngresar.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnIngresar.setText("Ingresar");
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnIngresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        backGround.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, 120, 40));

        Ingresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Ingresar.setForeground(new java.awt.Color(255, 255, 255));
        Ingresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ingresar.setText("INGRESAR");
        Ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backGround.add(Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backGround, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void txtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMousePressed
        if(String.valueOf(txtContraseña.getPassword()).isEmpty()){
            txtContraseña.setText("****************");
            txtContraseña.setForeground(Color.gray); 
        }
        if(txtUsuario.getText().equals("Ingrese su nombre de usuario")){
            txtUsuario.setText("");
            txtUsuario.setForeground(Color.black);
        }
                       
        
    }//GEN-LAST:event_txtUsuarioMousePressed

    private void txtContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraseñaMousePressed
        if(String.valueOf(txtContraseña.getPassword()).equals("****************")){
            txtContraseña.setText("");
            txtContraseña.setForeground(Color.black);
        }
                
        if(txtUsuario.getText().isEmpty()){
            txtUsuario.setText("Ingrese su nombre de usuario");
            txtUsuario.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtContraseñaMousePressed

    private void btnIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseClicked
        boolean estado1 = false;
        boolean estado2 = false;
        String usuario = txtUsuario.getText();    
        String contraseña = "";
        char[] password = txtContraseña.getPassword();
        for(int i=0; i<password.length; i++){
            contraseña += password[i];
        }
        
        /* LECTURA DEL ARCHIVO QUE ALMACENA LOS DATOS DE LOS ADMINISTRADORES, 
            entre ello el nombre de usuario y contraseña */
        leerArchivoAdministradores();        
        
        // VALIDANDO EL USUARIO Y AL CONTRASEÑA ingresados
        for(int i=0; i<listaAuxAdministradores.size(); i++){
            if(usuario.equals(listaAuxAdministradores.get(i).getUsuario())){
                estado1 = true;
                if(contraseña.equals(listaAuxAdministradores.get(i).getContraseña())){
                estado2 = true;
                }
            }           
        }
        if(estado1==true || estado2 ==true){
            JOptionPane.showMessageDialog(this,"Bienvenido a SUNWAY");
            Menu menu = new Menu();
            menu.setVisible(true);
            this.dispose();
            }
        else{
            JOptionPane.showMessageDialog(this,"Usuario y/o contraseña incorrecta!!!!");                       
            }  
    }//GEN-LAST:event_btnIngresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioPlataforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioPlataforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioPlataforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioPlataforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioPlataforma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ingresar;
    private javax.swing.JPanel backGround;
    private javax.swing.JLabel btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel logo;
    private sistemareservahospedajes.SistemaReservaHospedajes sistemaReservaHospedajes1;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
    
    
    private void leerArchivoAdministradores() {
        try{
                       
            File archivo =new File("administradores.txt");
            FileReader fr = new FileReader(archivo);
            BufferedReader br = new BufferedReader(fr);
            
            String linea;
            while((linea = br.readLine()) !=null){
                String nom = linea;
                String ape = br.readLine();
                String dni = br.readLine();
                String usuarioArchivo = br.readLine();
                String contraseñaArchivo = br.readLine();
                
                Administrador administrador = new Administrador(usuarioArchivo, contraseñaArchivo);
                this.listaAuxAdministradores.add(administrador);
            } fr.close();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al leer Archivo");
            e.printStackTrace();
        }
    }

}
